import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PolyfireProvider } from "polyfire-js/hooks";
import { SpeechProvider } from "./context/SpeechContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <script type="module">
  // Import the functions you need from the SDKs you need
  import { initializeApp } from "https://www.gstatic.com/firebasejs/10.7.2/firebase-app.js";
  import { getAnalytics } from "https://www.gstatic.com/firebasejs/10.7.2/firebase-analytics.js";
  // TODO: Add SDKs for Firebase products that you want to use
  // https://firebase.google.com/docs/web/setup#available-libraries

  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  const firebaseConfig = {
    apiKey: "AIzaSyA6ynlJODZKAQESjmCnP7H_ZNwB7FOtZYs",
    authDomain: "chatlingo-35af9.firebaseapp.com",
    projectId: "chatlingo-35af9",
    storageBucket: "chatlingo-35af9.appspot.com",
    messagingSenderId: "1080895166811",
    appId: "1:1080895166811:web:4a6485a29e5aaa63b0227e",
    measurementId: "G-FKECWJR5ST"
  };

  // Initialize Firebase
  const app = initializeApp(firebaseConfig);
  const analytics = getAnalytics(app);
</script>
      <body className={inter.className}>
        <PolyfireProvider project={"test_50"}>
          <SpeechProvider>{children}</SpeechProvider>
        </PolyfireProvider>
      </body>
    </html>
  );
}
